name: Github

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  update-icons:
    name: Update Icons
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo code
        uses: actions/checkout@v2
      - name: Run the update icons script
        shell: pwsh
        run: |
          cd .github/scripts
          ./update_icons.ps1
